version: "3.5"

services:

  api:
    image: joaogabrielferr/api-spring-boot:0.1
    container_name: api-spring-boot
    environment:
      DATABASE_URL: jdbc:postgresql://db-postgres:5432/postgres_db
      DATABASE_USER: postgres_user
      DATABASE_PASSWORD: postgres_password
    depends_on:
      - db-postgres
    ports:
      - "8080:8080"

  db-postgres:
    image: postgres:alpine
    container_name: api-spring-boot-postgres
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"